package com.example.esp32dashcam.utils

import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.RandomAccessFile
import java.nio.ByteBuffer
import java.nio.ByteOrder

object AviMerger {

    const val AVI_HEADER_SIZE = 224

    data class AviInfo(
        val width: Int,
        val height: Int,
        val fps: Int,
        val totalFrames: Int
    )

    /**
     * Reads metadata from standard 224-byte AVI header generated by ESP32 Dashcam.
     */
    fun readAviInfo(file: File): AviInfo {
        if (file.length() < AVI_HEADER_SIZE) {
            throw IllegalArgumentException("El archivo ${file.name} es demasiado pequeño para ser un AVI válido.")
        }

        FileInputStream(file).use { fis ->
            val header = ByteArray(AVI_HEADER_SIZE)
            val read = fis.read(header)
            if (read < AVI_HEADER_SIZE) throw IllegalArgumentException("Error al leer cabecera AVI de ${file.name}")

            val bb = ByteBuffer.wrap(header).order(ByteOrder.LITTLE_ENDIAN)

            // Validar formato básico RIFF AVI
            val riff = String(header, 0, 4)
            val avi = String(header, 8, 4)
            if (riff != "RIFF" || avi != "AVI ") {
                throw IllegalArgumentException("Archivo ${file.name} no tiene firma RIFF AVI válida")
            }

            val totalFrames = bb.getInt(48)
            val width = bb.getInt(64)
            val height = bb.getInt(68)
            var fps = bb.getInt(132)
            if (fps <= 0) fps = 3

            return AviInfo(width, height, fps, totalFrames)
        }
    }

    /**
     * Generates a standard 224-byte AVI MJPEG header byte buffer.
     */
    fun buildAviHeader(
        width: Int,
        height: Int,
        totalFrames: Int,
        fps: Int,
        moviSize: Long
    ): ByteArray {
        val buf = ByteBuffer.allocate(AVI_HEADER_SIZE).order(ByteOrder.LITTLE_ENDIAN)

        fun putStr(s: String) {
            for (c in s) buf.put(c.code.toByte())
        }

        // 1. RIFF
        putStr("RIFF")
        val riffSize = (moviSize + AVI_HEADER_SIZE - 8).toInt()
        buf.putInt(riffSize)
        putStr("AVI ")

        // 2. LIST hdrl
        putStr("LIST")
        buf.putInt(192)
        putStr("hdrl")

        // 2.1 avih
        putStr("avih")
        buf.putInt(56)
        val safeFps = if (fps > 0) fps else 3
        buf.putInt(1000000 / safeFps) // usec per frame
        buf.putInt(0) // max bytes
        buf.putInt(0) // padding
        buf.putInt(0x810) // flags: HASINDEX | TRUSTCKTYPE
        buf.putInt(totalFrames)
        buf.putInt(0) // initial frames
        buf.putInt(1) // streams
        buf.putInt(0) // suggested buffer size
        buf.putInt(width)
        buf.putInt(height)
        buf.putInt(0); buf.putInt(0); buf.putInt(0); buf.putInt(0) // reserved

        // 2.2 LIST strl
        putStr("LIST")
        buf.putInt(116)
        putStr("strl")

        // 2.2.1 strh
        putStr("strh")
        buf.putInt(56)
        putStr("vids")
        putStr("MJPG")
        buf.putInt(0) // flags
        buf.putInt(0) // priority / language
        buf.putInt(0) // initial frames
        buf.putInt(1) // scale
        buf.putInt(safeFps) // rate
        buf.putInt(0) // start
        buf.putInt(totalFrames)
        buf.putInt(0) // buffer size
        buf.putInt(-1) // quality
        buf.putInt(0) // sample size
        buf.putShort(0.toShort()); buf.putShort(0.toShort()) // rcFrame left, top
        buf.putShort(width.toShort()); buf.putShort(height.toShort()) // rcFrame right, bottom

        // 2.2.2 strf (BITMAPINFOHEADER 40 bytes)
        putStr("strf")
        buf.putInt(40)
        buf.putInt(40) // biSize
        buf.putInt(width)
        buf.putInt(height)
        buf.putShort(1.toShort()) // biPlanes
        buf.putShort(24.toShort()) // biBitCount
        putStr("MJPG")
        buf.putInt(width * height * 3) // biSizeImage
        buf.putInt(0) // biXPelsPerMeter
        buf.putInt(0) // biYPelsPerMeter
        buf.putInt(0) // biClrUsed
        buf.putInt(0) // biClrImportant

        // 3. LIST movi
        putStr("LIST")
        buf.putInt(moviSize.toInt())
        putStr("movi")

        return buf.array()
    }

    /**
     * Losslessly concatenates multiple AVI files into a single destination AVI file.
     * Takes <1 second and zero CPU re-encoding.
     *
     * @param inputFiles Sequence of AVI files to merge in order
     * @param outputFile Destination AVI file
     * @param onProgress Callback (currentFileIndex, totalFiles)
     */
    fun mergeAviFiles(
        inputFiles: List<File>,
        outputFile: File,
        onProgress: ((current: Int, total: Int) -> Unit)? = null
    ): Boolean {
        if (inputFiles.isEmpty()) return false
        if (inputFiles.size == 1) {
            inputFiles[0].copyTo(outputFile, overwrite = true)
            return true
        }

        var totalFrames = 0
        var moviPayloadSize = 4L // 'movi' FourCC is 4 bytes inside the LIST chunk
        val firstInfo = readAviInfo(inputFiles[0])

        // First pass: validate and calculate total frames and total movi payload
        for ((idx, file) in inputFiles.withIndex()) {
            val info = readAviInfo(file)
            totalFrames += info.totalFrames
            val filePayload = file.length() - AVI_HEADER_SIZE
            if (filePayload > 0) {
                moviPayloadSize += filePayload
            }
        }

        val headerBytes = buildAviHeader(
            width = firstInfo.width,
            height = firstInfo.height,
            totalFrames = totalFrames,
            fps = firstInfo.fps,
            moviSize = moviPayloadSize
        )

        // Write merged file
        FileOutputStream(outputFile).use { fos ->
            // Write unified 224-byte AVI header
            fos.write(headerBytes)

            // Write raw frame chunks from each video (everything past byte 224)
            val buffer = ByteArray(64 * 1024)
            for ((index, file) in inputFiles.withIndex()) {
                onProgress?.invoke(index + 1, inputFiles.size)
                FileInputStream(file).use { fis ->
                    // Skip 224 bytes of original AVI header
                    val skipped = fis.skip(AVI_HEADER_SIZE.toLong())
                    if (skipped == AVI_HEADER_SIZE.toLong()) {
                        var bytesRead: Int
                        while (fis.read(buffer).also { bytesRead = it } != -1) {
                            fos.write(buffer, 0, bytesRead)
                        }
                    }
                }
            }
            fos.flush()
        }

        return true
    }
}
